apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-fe
  namespace: sandbox
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
      - name: postgrest
        image: qroksera.com/sandbox/postgrest-fe:202407240127
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
  namespace: sandbox
spec:
  type: NodePort
  selector:
    app: postgrest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # NodePortの範囲は30000-32767の間で指定
