apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: sandbox
  labels:
    app: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgre
                  key: uri
            - name: PGRST_DB_SCHEMA
              value: "hippo"
            - name: PGRST_DB_ANON_ROLE
              value: "hippo"
            - name: PGRST_SERVER_PROXY_URI
              value: "http://localhost:4000"
